version: '3'
services:
  v2board:
    image: monlor/v2board
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAIN: http://localhost
    restart: unless-stopped
    links:
     - mysql
  mysql:
    image: mysql:5.7.29
    restart: unless-stopped
    environment: 
      MYSQL_ROOT_PASSWORD: v2boardisbest
      MYSQL_DATABASE: v2board